version: '3.1'

services:
  radiofm:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
        PORT: 8080
        DATABASE_URL: postgres://postgres:psqlpass@postgre:5432/radiofm
        LOCAL_DATA_PATH: /app/data
        JWT_SECRET: secret
        CLIENT_URL: http://localhost:8080
        SERVER_URL: http://localhost:8080
    # volumes:
    #   - ./data:/app/data

  postgre:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: psqlpass
      POSTGRES_USER: postgres