import { Box, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

import Header from '../components/Header';
import { useUserData, useUserInterface } from '../components/hooks/userContext';
import { api } from '../util/api';

import styles from '../styles/Home.module.css';

const Account: NextPage = () => {
  const user = useUserData();
  const router = useRouter();
  const [error, setError] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const userhandler = useUserInterface();

  useEffect(() => {
    if (user?.role === 'GUEST') {
      void router.push('/');
    }
  }, [user, router]);

  const deleteAccount = async (event: React.MouseEvent<HTMLElement>) => {
    event.preventDefault();
    setLoading(true);

    try {
      await api.user.deleteAccount();
      await userhandler?.getSelf();
      void router.push('/delete-account');
    } catch (e) {
      setError(true);
      setLoading(false);
    }
  };

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Box display="flex" flex="1" sx={{ flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <h1 className={styles.title}>Account Details</h1>
        <Typography variant="h6" fontWeight="bold">
          {`Username: ${user?.username}`}
        </Typography>

        <Typography>
          <button className="passbutton" onClick={() => router.push('/change-username')}>
            Change Username
          </button>
        </Typography>
        <Typography>
          <button className="passbutton" onClick={() => router.push('/change-password')}>
            Change Password
          </button>
        </Typography>
        <Typography>
          <button className="passbutton" onClick={deleteAccount}>
            Delete Account
          </button>
        </Typography>
      </Box>
    </Box>
  );
};

export default Account;
