import { Box, Typography, Button } from '@mui/material';
import { useRouter } from 'next/router'
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import Header from '../components/Header';
import { useUserData } from '../components/hooks/userContext';
import ParticlesComponent from '../components/Particles';
import VolumeSlider from '../components/VolumeSlider';
import styles from '../styles/Home.module.css';


const Home: NextPage = () => {
  const user = useUserData();
  const router = useRouter();

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <ParticlesComponent />
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Box display="flex" flex="1" sx={{ flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <h1 className={styles.title}>Account Details</h1>   
        <Typography variant="h6" fontWeight="bold">
        {`Username: ${user?.username}`}
        </Typography>
        <Typography variant="h6" fontWeight="bold">
        {`User ID: ${user?.id}`}
        </Typography>
        <Typography>
            <button className="passbutton"  onClick={() => router.push('/change-username')}>
                Change Username
            </button>
        </Typography>
        <Typography>
            <button className="passbutton"  onClick={() => router.push('/change-password')}>
                Change Password
            </button>
        </Typography>
      </Box>
      <VolumeSlider />
    </Box>
  );
};

export default Home;
