import { Box, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';

import type { ApiUser } from '../../server/src/apiTypes/user';
import Header from '../components/Header';
import { useUserData } from '../components/hooks/userContext';
import ParticlesComponent from '../components/Particles';
import { api } from '../util/api';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const user = useUserData();
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(false);

  const deleteAccount = async (event: React.MouseEvent<HTMLElement>) => {
    event.preventDefault();
    let deleteAccount: ApiUser | undefined = undefined;
    deleteAccount = await api.user.deleteAccount();
  };

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <ParticlesComponent />
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Box display="flex" flex="1" sx={{ flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <h1 className={styles.title}>Account Details</h1>
        <Typography variant="h6" fontWeight="bold">
          {`Username: ${user?.username}`}
        </Typography>

        <Typography>
          <button className="passbutton" onClick={() => router.push('/change-username')}>
            Change Username
          </button>
        </Typography>
        <Typography>
          <button className="passbutton" onClick={() => router.push('/change-password')}>
            Change Password
          </button>
        </Typography>
        <Typography>
          <button className="passbutton" onClick={deleteAccount}>
            Delete Account
          </button>
        </Typography>
      </Box>
    </Box>
  );
};

export default Home;
