import { Box } from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';

import type { ApiUser } from '../../server/src/apiTypes/user';
import { useUserData, useUserInterface } from '../components/hooks/userContext';
import UserUpdate from '../components/UserUpdate';
import { api } from '../util/api';

const ChangeUsername = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<boolean>(false);

  const user = useUserData();
  const userhandler = useUserInterface();
  const router = useRouter();

  useEffect(() => {
    if (user?.role == 'GUEST') {
      void router.push('/');
    }
  }, [user, router]);

  const updateUsername = async (UsernameInput: string) => {
    setLoading(true);

    let newUsername: ApiUser | undefined = undefined;

    if (UsernameInput) {
      newUsername = await api.user.changeUsername({ username: UsernameInput });
    }

    if (!newUsername) {
      setError(true);
    } else {
      void userhandler?.getSelf();
      void router.push('/account');
    }
    setLoading(false);
  };

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserUpdate updateUser={updateUsername} error={error} loading={loading} />
    </Box>
  );
};

export default ChangeUsername;
