import { Box, Typography, Button, TextField } from '@mui/material';
import { useRouter } from 'next/router'
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';


import Header from '../components/Header';
import { useUserData } from '../components/hooks/userContext';
import ParticlesComponent from '../components/Particles';
import VolumeSlider from '../components/VolumeSlider';
import { ApiUser, UserCredentials } from '../../server/src/apiTypes/user';
import { api } from '../util/api';

const ChangePassword = () => {
  const [password, setNewPassword] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);

  const user = useUserData();
  const router = useRouter();

  useEffect(() => {
    if (user?.role == 'GUEST') {
      void router.push('/');
    }
  }, [user, router]);

  const updatePassword = async (event: React.MouseEvent<HTMLElement>) => {
    event.preventDefault();
    setLoading(true);

    let newPass: ApiUser | undefined = undefined;

    if (password) {
      newPass = await api.user?.changePassword({password})
    }

    setLoading(false);
  };

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <ParticlesComponent />
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box height="100vh" display="flex" alignItems="center" justifyContent="center">
      <form>
      <Box display="flex" flexDirection="column" sx={{ width: '25rem' }}>
          <Typography variant="h4" sx={{ marginBottom: '.5rem' }}>
            Update Password
          </Typography>
          <TextField
            variant="filled"
            placeholder="New Password"
            autoComplete="new-password"
            type="password"
            value={password}
            onChange={(event: React.ChangeEvent<HTMLInputElement>) => setNewPassword(event.target.value)}
            sx={{
              '& .MuiInputBase-input': {
                backgroundColor: '#111',
                color: '#fff',
                padding: '1rem',
                borderRadius: '.3rem',
              },
            }}
          />
          <Box display="flex" sx={{ marginTop: '1rem' }}>
            <Button variant="outlined" sx={{ marginRight: '1rem' }} onClick={() => router.push('/')}>
              Cancel
            </Button>
            <Button variant="contained" onClick={updatePassword}>
              {!loading ? 'Update' : 'Password Changed!'}
            </Button>
          </Box>
        </Box>
      </form>
      </Box>
      <VolumeSlider />
    </Box>
  );
};

export default ChangePassword;