import { Box, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

import Header from '../components/Header';
import { useSongHandler } from '../components/hooks/songContext';
import ParticlesComponent from '../components/Particles';
import VolumeSlider from '../components/VolumeSlider';
import { api } from '../util/api';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const songHandler = useSongHandler();
  const router = useRouter();

  const likeHandler = async (songId: string | null, liked: boolean) => {
    if (!songId) {
      return;
    }

    if (liked) {
      await api.user.unlikeSong({ songId });
    } else {
      await api.user.likeSong({ songId });
    }

    void songHandler?.getSongLiked(songId);
  };

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <ParticlesComponent />
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Box display="flex" flex="1" sx={{ flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
        <h1 className={styles.title}>Account has been deleted!</h1>
        <Typography>
          <button className="passbutton" onClick={() => router.push('/')}>
            Return to Home Page
          </button>
        </Typography>
      </Box>
      <VolumeSlider />
    </Box>
  );
};

export default Home;
