import { Box } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';

import type { ApiSongInfo } from '../../server/src/apiTypes/song';
import Header from '../components/Header';
import { useSong, useSongHandler } from '../components/hooks/songContext';
import LikedSongs from '../components/LikedSongs';
import { api } from '../util/api';

const Home: NextPage = () => {
  const [songs, setSongs] = useState<ApiSongInfo[]>([]);
  const song = useSong();

  const getLikedSongs = async () => {
    const songList = await api.user.getLikedSongs();
    setSongs(songList);
  };

  useEffect(() => {
    void getLikedSongs();
  }, []);

  const songHandler = useSongHandler();

  return (
    <Box display="flex" flexDirection="column" sx={{ height: '100vh' }}>
      <Head>
        <title>Now Listening to Radio.FM!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Box display="flex" flex="1" sx={{ flexDirection: 'row', justifyContent: 'center', alignItems: 'center' }}>
        {song?.song && (
          <>
            <LikedSongs songs={songs} refresh={getLikedSongs} />
          </>
        )}
      </Box>
    </Box>
  );
};

export default Home;
