name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.LEO_DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.LEO_DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --no-cache --tag ${{secrets.LEO_DOCKER_USER}}/radio.fm:$(date +%s) --tag ${{secrets.LEO_DOCKER_USER}}/radio.fm:latest

      - name: Docker Push
        run: docker push ${{secrets.LEO_DOCKER_USER}}/radio.fm:latest

      - name: Install flyctl
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly Deploy
        run: cd ./fly-configs/leo && flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.LEO_FLY_TOKEN }}
